name: Build and Push Extension

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  push-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: version
        run: echo "::set-output name=TAG::$(cat VERSION)"

      - name: Run Makefile push-extension
        run: make push-extension TAG=${{ steps.version.outputs.TAG }}